In [1]:
import pandas as pd
df=pd.read_csv('오뚜기40개변수추출.csv',engine='python')

In [2]:
del df['Unnamed: 0']
df.head()

,mean_5,high,mean,low,open,enhwa,volume,h,pound,hello8,...,BRENT,wian,Kosdaq,maxatthatwindtime,fire,b,j,Kospi,close,beforeclose
0,139200.0,143000.0,1978.92,138500.0,141500.0,1432.28,3060.0,7.51,1921.29,8.4,...,49.62,193.49,339.76,1531,1.5763,33300357.0,4.22,1157.40,136500.0,141000
1,139000.0,143500.0,1943.18,136000.0,143500.0,1402.08,6162.0,7.46,1918.99,4.9,...,50.53,191.39,342.77,1408,1.6263,33300357.0,4.24,1173.57,135500.0,136500
2,138200.0,140500.0,1937.88,134500.0,136500.0,1405.45,8069.0,7.45,1957.67,5.0,...,48.76,191.94,348.41,1515,1.5431,33300357.0,4.35,1194.28,134000.0,135500
3,135900.0,136000.0,1951.54,132000.0,135000.0,1394.83,8728.0,7.25,1951.07,8.6,...,44.67,189.08,356.13,1620,1.5196,33300357.0,4.16,1228.17,132500.0,134000
4,133800.0,137000.0,1924.92,132500.0,136500.0,1447.12,7495.0,7.43,2012.68,6.2,...,44.42,193.28,356.52,1427,1.4877,33300357.0,4.37,1205.70,130500.0,132500

In [3]:
df['yn']=df['close'] - df['beforeclose']
df.head()

,mean_5,high,mean,low,open,enhwa,volume,h,pound,hello8,...,wian,Kosdaq,maxatthatwindtime,fire,b,j,Kospi,close,beforeclose,yn
0,139200.0,143000.0,1978.92,138500.0,141500.0,1432.28,3060.0,7.51,1921.29,8.4,...,193.49,339.76,1531,1.5763,33300357.0,4.22,1157.40,136500.0,141000,-4500.0
1,139000.0,143500.0,1943.18,136000.0,143500.0,1402.08,6162.0,7.46,1918.99,4.9,...,191.39,342.77,1408,1.6263,33300357.0,4.24,1173.57,135500.0,136500,-1000.0
2,138200.0,140500.0,1937.88,134500.0,136500.0,1405.45,8069.0,7.45,1957.67,5.0,...,191.94,348.41,1515,1.5431,33300357.0,4.35,1194.28,134000.0,135500,-1500.0
3,135900.0,136000.0,1951.54,132000.0,135000.0,1394.83,8728.0,7.25,1951.07,8.6,...,189.08,356.13,1620,1.5196,33300357.0,4.16,1228.17,132500.0,134000,-1500.0
4,133800.0,137000.0,1924.92,132500.0,136500.0,1447.12,7495.0,7.43,2012.68,6.2,...,193.28,356.52,1427,1.4877,33300357.0,4.37,1205.70,130500.0,132500,-2000.0

In [4]:
df.drop(['close'], inplace=True, axis=1)

In [5]:
def stockflow(x):
    if x >= 0:
        return 1
    else:
        return 0
df['yn'] = df.yn.map(lambda x: stockflow(x))
df.head()

,mean_5,high,mean,low,open,enhwa,volume,h,pound,hello8,...,BRENT,wian,Kosdaq,maxatthatwindtime,fire,b,j,Kospi,beforeclose,yn
0,139200.0,143000.0,1978.92,138500.0,141500.0,1432.28,3060.0,7.51,1921.29,8.4,...,49.62,193.49,339.76,1531,1.5763,33300357.0,4.22,1157.40,141000,0
1,139000.0,143500.0,1943.18,136000.0,143500.0,1402.08,6162.0,7.46,1918.99,4.9,...,50.53,191.39,342.77,1408,1.6263,33300357.0,4.24,1173.57,136500,0
2,138200.0,140500.0,1937.88,134500.0,136500.0,1405.45,8069.0,7.45,1957.67,5.0,...,48.76,191.94,348.41,1515,1.5431,33300357.0,4.35,1194.28,135500,0
3,135900.0,136000.0,1951.54,132000.0,135000.0,1394.83,8728.0,7.25,1951.07,8.6,...,44.67,189.08,356.13,1620,1.5196,33300357.0,4.16,1228.17,134000,0
4,133800.0,137000.0,1924.92,132500.0,136500.0,1447.12,7495.0,7.43,2012.68,6.2,...,44.42,193.28,356.52,1427,1.4877,33300357.0,4.37,1205.70,132500,0

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:39], df["yn"], test_size=0.33, random_state=42)

In [7]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

seed = 7
model = LogisticRegression().fit(X_train, y_train)

predicted = model.predict(X_test)
report = classification_report(y_test, predicted)
print(report)
matrix = confusion_matrix(y_test, predicted)
print(matrix)

             precision    recall  f1-score   support

          0       0.63      0.39      0.48       371
          1       0.58      0.79      0.67       403

avg / total       0.61      0.60      0.58       774

[[143 228]
 [ 84 319]]

In [8]:
from sklearn.externals import joblib



filename = 'ddugi_classifier.joblib.pkl'
_ = joblib.dump(model, filename, compress=9)

model2 = joblib.load(filename)
model2

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [9]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.svm import SVC  
svm = SVC(kernel='rbf', C=10, gamma=0.1).fit(X_train, y_train)
predicted = svclassifier.predict(X_test)
report = classification_report(y_test, predicted)
matrix = confusion_matrix(y_test, predicted)

print(report)
print(matrix)

SyntaxError: invalid syntax (<ipython-input-9-3d01600f3de5>, line 5)

In [12]:
import pandas
from sklearn.svm import SVC
from sklearn import metrics
def run_svc_model(kernel, penalty, gamma='auto'):
    model = SVC(kernel=kernel, C=penalty, gamma=gamma)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    print('confusion matrix')
    print(metrics.confusion_matrix(y_test, y_pred))
    print('accuracy : {}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('precision : {}'.format(metrics.precision_score(y_test, y_pred, pos_label='four')))
    print('recall : {}'.format(metrics.recall_score(y_test, y_pred, pos_label='four')))
    print('F1 : {}'.format(metrics.f1_score(y_test, y_pred, pos_label='four')))
    return model

In [13]:
svc_rbf1 = run_svc_model('rbf', 1)

confusion matrix
[[  0 371]
 [  0 403]]
accuracy : 0.520671834625323

C:\Users\acorn\AppData\Local\conda\conda\envs\xgboost\lib\site-packages\sklearn\metrics\classification.py:1030: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if pos_label not in present_labels:

ValueError: pos_label='four' is not a valid label: array([0, 1], dtype=int64)